<a href="https://colab.research.google.com/github/PethrusSouza/Exercicios_Python/blob/main/MercadoLivre_aula06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Web scraping com Python
# Buscando produtos no Mercado Livre

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np

In [ ]:
url_base = 'https://lista.mercadolivre.com.br/'

In [ ]:
produto_nome = input('Qual produto você procura? ')

Qual produto você procura? galaxy

In [ ]:
response = requests.get(url_base + produto_nome)
print(response)

<Response [200]>

In [ ]:
response.text

'\n<!DOCTYPE html>\n<html lang="pt-BR">\n<head><link rel="preconnect" href="https://www.google-analytics.com"/><link rel="preconnect" href="https://www.google.com"/><link rel="preconnect" href="https://data.mercadolibre.com"/><link rel="preconnect" href="https://http2.mlstatic.com"/><link rel="preconnect" href="https://stats.g.doubleclick.net"/><link rel="preconnect" href="https://analytics.mercadolivre.com.br"/><link rel="preconnect" href="https://analytics.mercadolivre.com"/><link rel="preconnect" href="https://www.google.com.br"/><script type=\'text/javascript\' nonce="V2/xzcQr3yS1SStajWRGBQ==">window.NREUM||(NREUM={});NREUM.info = {"agent":"","beacon":"bam.nr-data.net","errorBeacon":"bam.nr-data.net","licenseKey":"NRBR-8547a290c864571ffcc","applicationID":"1729522169","agentToken":null,"applicationTime":765.346243,"transactionName":"bgQDMEcFXkJZBkYNWldOJBxFFlVCSw9BS3J8NU5LHw==","queueTime":0,"ttGuid":"2879607f54b120f7"}; (window.NREUM||(NREUM={})).init={privacy:{cookies_enabled:true},ajax:{deny_list:["bam.nr-data.net"]},distributed_tracing:{enabled:true}};(window.NREUM||(NREUM={})).loader_config={agentID:"1834861763",accountID:"989586",trustKey:"1709707",xpid:"XQ4OVF5VGwIHVlhXBQMGUF0=",licenseKey:"NRBR-8547a290c864571ffcc",applicationID:"1729522169"};;/*! For license information please see nr-loader-spa-1.267.0.min.js.LICENSE.txt */\n(()=>{var e,t,r={8122:(e,t,r)=>{"use strict";r.d(t,{a:()=>i});var n=r(944);function i(e,t){try{if(!e||"object"!=typeof e)return(0,n.R)(3);if(!t||"object"!=typeof t)return(0,n.R)(4);const r=Object.create(Object.getPrototypeOf(t),Object.getOwnPropertyDescriptors(t)),o=0===Object.keys(r).length?e:r;for(let a in o)if(void 0!==e[a])try{if(null===e[a]){r[a]=null;continue}Array.isArray(e[a])&&Array.isArray(t[a])?r[a]=Array.from(new Set([...e[a],...t[a]])):"object"==typeof e[a]&&"object"==typeof t[a]?r[a]=i(e[a],t[a]):r[a]=e[a]}catch(e){(0,n.R)(1,e)}return r}catch(e){(0,n.R)(2,e)}}},2555:(e,t,r)=>{"use strict";r.d(t,{Vp:()=>c,fn:()=>s,x1:()=>u});var n=r(384),i=r(8122);const o={beacon:n.NT.beacon,errorBeacon:n.NT.errorBeacon,licenseKey:void 0,applicationID:void 0,sa:void 0,queueTime:void 0,applicationTime:void 0,ttGuid:void 0,user:void 0,account:void 0,product:void 0,extra:void 0,jsAttributes:{},userAttributes:void 0,atts:void 0,transactionName:void 0,tNamePlain:void 0},a={};function s(e){try{const t=c(e);return!!t.licenseKey&&!!t.errorBeacon&&!!t.applicationID}catch(e){return!1}}function c(e){if(!e)throw new Error("All info objects require an agent identifier!");if(!a[e])throw new Error("Info for ".concat(e," was never set"));return a[e]}function u(e,t){if(!e)throw new Error("All info objects require an agent identifier!");a[e]=(0,i.a)(t,o);const r=(0,n.nY)(e);r&&(r.info=a[e])}},9417:(e,t,r)=>{"use strict";r.d(t,{D0:()=>h,gD:()=>p,xN:()=>g});var n=r(993);const i=e=>{if(!e||"string"!=typeof e)return!1;try{document.createDocumentFragment().querySelector(e)}catch{return!1}return!0};var o=r(2614),a=r(944),s=r(384),c=r(8122);const u="[data-nr-mask]",d=()=>{const e={mask_selector:"*",block_selector:"[data-nr-block]",mask_input_options:{color:!1,date:!1,"datetime-local":!1,email:!1,month:!1,number:!1,range:!1,search:!1,tel:!1,text:!1,time:!1,url:!1,week:!1,textarea:!1,select:!1,password:!0}};return{ajax:{deny_list:void 0,block_internal:!0,enabled:!0,harvestTimeSeconds:10,autoStart:!0},distributed_tracing:{enabled:void 0,exclude_newrelic_header:void 0,cors_use_newrelic_header:void 0,cors_use_tracecontext_headers:void 0,allowed_origins:void 0},feature_flags:[],generic_events:{enabled:!0,harvestTimeSeconds:30,autoStart:!0},harvest:{tooManyRequestsDelay:60},jserrors:{enabled:!0,harvestTimeSeconds:10,autoStart:!0},logging:{enabled:!0,harvestTimeSeconds:10,autoStart:!0,level:n.p_.INFO},metrics:{enabled:!0,autoStart:!0},obfuscate:void 0,page_action:{enabled:!0},page_view_event:{enabled:!0,autoStart:!0},page_view_timing:{enabled:!0,harvestTimeSeconds:30,autoStart:!0},privacy:{cookies_enabled:!0},proxy:{assets:void 0,beacon:void 0},session:{expiresMs:o.wk,inactiveMs:o.BB},session_replay:{autoStart:!0,enabled:!1,harvestTimeSeconds:60,preload:!1,sampling_rate:10,error_sampling_rate:100,collect_fonts:!1,inline_images:!1,fix_stylesheets:!0,mask_all_inputs:!0,get mask_text_selector(){return e.mask_selector},set mask_text_selector(t){i(t)?e.mask_selector="".concat(t,",").concat(u):""===t||null===t?e.mask_selector=u:(0,a.R)(5,t)},get block_class(){return"nr-block"},get ignore_class(){return"nr-ignore"},get mask_text_class(){return"nr-mask"},get block_selector(){return e.block_selector},set block_selector(t){i(t)?e.block_selector+=",".concat(t):""!==t&&(0,a.R)(6,t)},get mask_input_options(){return e.mask_input_options},set mask_input_options(t){t&&"object"==typeof t?e.mask_input_options={...t,password:!0}:(0,a.R)(7,t)}},session_trace:{enabled:!0,harvestTimeSeconds:10,autoStart:!0},soft_navigations:{enabled:!0,harvestTimeSeconds:10,autoStart:!0},spa:{enabled:!0,harvestTimeSeconds:10,autoStart:!0},ssl:void 0}},l={},f="All configuration objects require an agent identifier!";function h(e){if(!e)throw new Error(f);if(!l[e])throw new Error("Configuration for ".concat(e," was never set"));return l[e]}function g(e,t){if(!e)throw new Error(f);l[e]=(0,c.a)(t,d());const r=(0,s.nY)(e);r&&(r.init=l[e])}function p(e,t){if(!e)throw new Error(f);var r=h(e);if(r){for(var n=t.split("."),i=0;i<n.length-1;i++)if("object"!=typeof(r=r[n[i]]))return;r=r[n[n.length-1]]}return r}},5603:(e,t,r)=>{"use strict";r.d(t,{a:()=>c,o:()=>s});var n=r(384),i=r(8122);const o={accountID:void 0,trustKey:void 0,agentID:void 0,licenseKey:void 0,applicationID:void 0,xpid:void 0},a={};function s(e){if(!e)throw new Error("All loader-config objects require an agent identifier!");if(!a[e])throw new Error("LoaderConfig for ".concat(e," was never set"));return a[e]}function c(e,t){if(!e)throw new Error("All loader-config objects require an agent identifier!");a[e]=(0,i.a)(t,o);const r=(0,n.nY)(e);r&&(r.loader_config=a[e])}},3371:(e,t,r)=>{"use strict";r.d(t,{V:()=>f,f:()=>l});var n=r(8122),i=r(384),o=r(6154),a=r(9324);let s=0;const c={buildEnv:a.F3,distMethod:a.Xs,version:a.xv,originTime:o.WN},u={customTransaction:void 0,disabled:!1,isolatedBacklog:!1,loaderType:void 0,maxBytes:3e4,onerror:void 0,origin:""+o.gm.location,ptid:void 0,releaseIds:{},appMetadata:{},session:void 0,denyList:void 0,timeKeeper:void 0,obfuscator:void 0},d={};function l(e){if(!e)throw new Error("All runtime objects require an agent identifier!");if(!d[e])throw new Error("Runtime for ".concat(e," was never set"));return d[e]}function f(e,t){if(!e)throw new Error("All runtime objects require an agent identifier!");d[e]={...(0,n.a)(t,u),...c},Object.hasOwnProperty.call(d[e],"harvestCount")||Object.defineProperty(d[e],"harvestCount",{get:()=>++s});const r=(0,i.nY)(e);r&&(r.runtime=d[e])}},9324:(e,t,r)=>{"use strict";r.d(t,{F3:()=>i,Xs:()=>o,Yq:()=>a,xv:()=>n});const n="1.267.0",i="PROD",o="CDN",a="2.0.0-alpha.12"},6154:(e,t,r)=>{"use strict";r.d(t,{A4:()=>s,OF:()=>d,RI:()=>i,Vr:()=>h,WN:()=>g,bv:()=>o,gm:()=>a,lR:()=>f,m:()=>u,mw:()=>c,sb:()=>l});var n=r(1863);const i="undefined"!=typeof window&&!!window.document,o="undefined"!=typeof WorkerGlobalScope&&("undefined"!=typeof self&&self instanceof WorkerGlobalScope&&self.navigator instanceof WorkerNavigator||"undefined"!=typeof globalThis&&globalThis instanceof WorkerGlobalScope&&globalThis.navigator instanceof WorkerNavigator),a=i?window:"undefined"!=typeof WorkerGlobalScope&&("undefined"!=typeof self&&self instanceof WorkerGlobalScope&&self||"undefined"!=typeof globalThis&&globalThis instanceof WorkerGlobalScope&&globalThis),s="complete"===a?.document?.readyState,c=Boolean("hidden"===a?.document?.visibilityState),u=""+a?.location,d=/iPad|iPhone|iPod/.test(a.navigator?.userAgent),l=d&&"undefined"==typeof SharedWorker,f=(()=>{const e=a.navigator?.userAgent?.match(/Firefox[/\\s](\\d+\\.\\d+)/);return Array.isArray(e)&&e.length>=2?+e[1]:0})(),h=!!a.navigator?.sendBeacon,g=Date.now()-(0,n.t)()},4777:(e,t,r)=>{"use strict";r.d(t,{J:()=>o});var n=r(944);const i={agentIdentifier:"",ee:void 0};class o{constructor(e){try{if("object"!=typeof e)return(0,n.R)(8);this.sharedContext={},Object.assign(this.sharedContext,i),Object.entries(e).forEach((([e,t])=>{Object.keys(i).includes(e)&&(this.sharedContext[e]=t)}))}catch(e){(0,n.R)(9,e)}}}},7295:(e,t,r)=>{"use strict";r.d(t,{Xv:()=>a,gX:()=>i,iW:()=>o});var n=[];function i(e){if(!e||o(e))return!1;if(0===n.length)return!0;for(var t=0;t<n.length;t++){var r=n[t];if("*"===r.hostname)return!1;if(s(r.hostname,e.hostname)&&c(r.pathname,e.pathname))return!1}return!0}function o(e){return void 0===e.hostname}function a(e){if(n=[],e&&e.length)for(var t=0;t<e.length;t++){let r=e[t];if(!r)continue;0===r.indexOf("http://")?r=r.substring(7):0===r.indexOf("https://")&&(r=r.substring(8));const i=r.indexOf("/");let o,a;i>0?(o=r.substring(0,i),a=r.substring(i)):(o=r,a="");let[s]=o.split(":");n.push({hostname:s,pathname:a})}}function s(e,t){return!(e.length>t.length)&&t.indexOf(e)===t.length-e.length}function c(e,t){return 0===e.indexOf("/")&&(e=e.substring(1)),0===t.indexOf("/")&&(t=t.substring(1)),""===e||e===t}},1687:(e,t,r)=>{"use strict";r.d(t,{Ak:()=>c,Ze:()=>l,x3:()=>u});var n=r(7836),i=r(3606),o=r(860),a=r(2646);const s={};function c(e,t){const r={staged:!1,priority:o.P[t]||0};d(e),s[e].get(t)||s[e].set(t,r)}function u(e,t){e&&s[e]&&(s[e].get(t)&&s[e].delete(t),h(e,t,!1),s[e].size&&f(e))}function d(e){if(!e)throw new Error("agentIdentifier required");s[e]||(s[e]=new Map)}function l(e="",t="feature",r=!1){if(d(e),!e||!s[e].get(t)||r)return h(e,t);s[e].get(t).staged=!0,f(e)}function f(e){const t=Array.from(s[e]);t.every((([e,t])=>t.staged))&&(t.sort(((e,t)=>e[1].priority-t[1].priority)),t.forEach((([t])=>{s[e].delete(t),h(e,t)})))}function h(e,t,r=!0){const o=e?n.ee.get(e):n.ee,s=i.i.handlers;if(!o.aborted&&o.backlog&&s){if(r){const e=o.backlog[t],r=s[t];if(r){for(let t=0;e&&t<e.length;++t)g(e[t],r);Object.entries(r).forEach((([e,t])=>{Object.values(t||{}).forEach((t=>{t[0]?.on&&t[0]?.context()instanceof a.y&&t[0].on(e,t[1])}))}))}}o.isolatedBacklog||delete s[t],o.backlog[t]=null,o.emit("drain-"+t,[])}}function g(e,t){var r=e[1];Object.values(t[r]||{}).forEach((t=>{var r=e[0];if(t[0]===r){var n=t[1],i=e[3],o=e[2];n.apply(i,o)}}))}},7836:(e,t,r)=>{"use strict";r.d(t,{P:()=>c,ee:()=>u});var n=r(384),i=r(8990),o=r(3371),a=r(2646),s=r(5607);const c="nr@context:".concat(s.W),u=function e(t,r){var n={},s={},d={},l=!1;try{l=16===r.length&&(0,o.f)(r).isolatedBacklog}catch(e){}var f={on:g,addEventListener:g,removeEventListener:function(e,t){var r=n[e];if(!r)return;for(var i=0;i<r.length;i++)r[i]===t&&r.splice(i,1)},emit:function(e,r,n,i,o){!1!==o&&(o=!0);if(u.aborted&&!i)return;t&&o&&t.emit(e,r,n);for(var a=h(n),c=p(e),d=c.length,l=0;l<d;l++)c[l].apply(a,r);var g=v()[s[e]];g&&g.push([f,e,r,a]);return a},get:m,listeners:p,context:h,buffer:function(e,t){const r=v();if(t=t||"feature",f.aborted)return;Object.entries(e||{}).forEach((([e,n])=>{s[n]=t,t in r||(r[t]=[])}))},abort:function(){f._aborted=!0,Object.keys(f.backlog).forEach((e=>{delete f.backlog[e]}))},isBuffering:function(e){return!!v()[s[e]]},debugId:r,backlog:l?{}:t&&"object"==typeof t.backlog?t.backlog:{},isolatedBacklog:l};return Object.defineProperty(f,"aborted",{get:()=>{let e=f._aborted||!1;return e||(t&&(e=t.aborted),e)}}),f;function h(e){return e&&e instanceof a.y?e:e?(0,i.I)(e,c,(()=>new a.y(c))):new a.y(c)}function g(e,t){n[e]=p(e).concat(t)}function p(e){return n[e]||[]}function m(t){return d[t]=d[t]||e(f,t)}function v(){return f.backlog}}(void 0,"globalEE"),d=(0,n.Zm)();d.ee||(d.ee=u)},2646:(e,t,r)=>{"use strict";r.d(t,{y:()=>n});class n{constructor(e){this.contextId=e}}},9908:(e,t,r)=>{"use strict";r.d(t,{d:()=>n,p:()=>i});var n=r(7836).ee.get("handle");function i(e,t,r,i,o){o?(o.buffer([e],i),o.emit(e,t,r)):(n.buffer([e],i),n.emit(e,t,r))}},3606:(e,t,r)=>{"use strict";r.d(t,{i:()=>o});var n=r(9908);o.on=a;var i=o.handlers={};function o(e,t,r,o){a(o||n.d,i,e,t,r)}function a(e,t,r,i,o){o||(o="feature"),e||(e=n.d);var a=t[o]=t[o]||{};(a[r]=a[r]||[]).push([e,i])}},3878:(e,t,r)=>{"use strict";r.d(t,{DD:()=>c,jT:()=>a,sp:()=>s});var n=r(6154);let i=!1,o=!1;try{const e={get passive(){return i=!0,!1},get signal(){return o=!0,!1}};n.gm.addEventListener("test",null,e),n.gm.removeEventListener("test",null,e)}catch(e){}function a(e,t){return i||o?{capture:!!e,passive:i,signal:t}:!!e}function s(e,t,r=!1,n){window.addEventListener(e,t,a(r,n))}function c(e,t,r=!1,n){document.addEventListener(e,t,a(r,n))}},5607:(e,t,r)=>{"use strict";r.d(t,{W:()=>n});const n=(0,r(9566).bz)()},9566:(e,t,r)=>{"use strict";r.d(t,{LA:()=>s,ZF:()=>c,bz:()=>a,el:()=>u});var n=r(6154);const i="xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx";function o(e,t){return e?15&e[t]:16*Math.random()|0}function a(){const e=n.gm?.crypto||n.gm?.msCrypto;let t,r=0;return e&&e.getRandomValues&&(t=e.getRandomValues(new Uint8Array(30))),i.split("").map((e=>"x"===e?o(t,r++).toString(16):"y"===e?(3&o()|8).toString(16):e)).join("")}function s(e){const t=n.gm?.crypto||n.gm?.msCrypto;let r,i=0;t&&t.getRandomValues&&(r=t.getRandomValues(new Uint8Array(e)));const a=[];for(var s=0;s<e;s++)a.push(o(r,i++).toString(16));return a.join("")}function c(){return s(16)}function u(){return s(32)}},2614:(e,t,r)=>{"use strict";r.d(t,{BB:()=>a,H3:()=>n,g:()=>u,iL:()=>c,tS:()=>s,uh:()=>i,wk:()=>o});const n="NRBA",i="SESSION",o=144e5,a=18e5,s={STARTED:"session-started",PAUSE:"session-pause",RESET:"session-reset",RESUME:"session-resume",UPDATE:"session-update"},c={SAME_TAB:"same-tab",CROSS_TAB:"cross-tab"},u={OFF:0,FULL:1,ERROR:2}},1863:(e,t,r)=>{"use strict";function n(){return Math.floor(performance.now())}r.d(t,{t:()=>n})},7485:(e,t,r)=>{"use strict";r.d(t,{D:()=>i});var n=r(6154);function i(e){if(0===(e||"").indexOf("data:"))return{protocol:"data"};try{const t=new URL(e,location.href),r={port:t.port,hostname:t.hostname,pathname:t.pathname,search:t.search,protocol:t.protocol.slice(0,t.protocol.indexOf(":")),sameOrigin:t.protocol===n.gm?.location?.protocol&&t.host===n.gm?.location?.host};return r.port&&""!==r.port||("http:"===t.protocol&&(r.port="80"),"https:"===t.protocol&&(r.port="443")),r.pathname&&""!==r.pathname?r.pathname.startsWith("/")||(r.pathname="/".concat(r.pathname)):r.pathname="/",r}catch(e){return{}}}},944:(e,t,r)=>{"use strict";function n(e,t){"function"==typeof console.debug&&console.debug("New Relic Warning: https://github.com/newrelic/newrelic-browser-agent/blob/main/docs/warning-codes.md#".concat(e),t)}r.d(t,{R:()=>n})},5284:(e,t,r)=>{"use strict";r.d(t,{t:()=>c,B:()=>s});var n=r(7836),i=r(6154);const o="newrelic";const a=new Set,s={};function c(e,t){const r=n.ee.get(t);s[t]??={},e&&"object"==typeof e&&(a.has(t)||(r.emit("rumresp",[e]),s[t]=e,a.add(t),function(e={}){try{i.gm.dispatchEvent(new CustomEvent(o,{detail:e}))}catch(e){}}({loaded:!0})))}},8990:(e,t,r)=>{"use strict";r.d(t,{I:()=>i});var n=Object.prototype.hasOwnProperty;function i(e,t,r){if(n.call(e,t))return e[t];var i=r();if(Object.defineProperty&&Object.keys)try{return Object.defineProperty(e,t,{value:i,writable:!0,enumerable:!1}),i}catch(e){}return e[t]=i,i}},6389:(e,t,r)=>{"use strict";function n(e,t=500,r={}){const n=r?.leading||!1;let i;return(...r)=>{n&&void 0===i&&(e.apply(this,r),i=setTimeout((()=>{i=clearTimeout(i)}),t)),n||(clearTimeout(i),i=setTimeout((()=>{e.apply(this,r)}),t))}}function i(e){let t=!1;return(...r)=>{t||(t=!0,e.apply(this,r))}}r.d(t,{J:()=>i,s:()=>n})},3304:(e,t,r)=>{"use strict";r.d(t,{A:()=>o});var n=r(7836);const i=()=>{const e=new WeakSet;return(t,r)=>{if("object"==typeof r&&null!==r){if(e.has(r))return;e.add(r)}return r}};function o(e){try{return JSON.stringify(e,i())}catch(e){try{n.ee.emit("internal-error",[e])}catch(e){}return""}}},5289:(e,t,r)=>{"use strict";r.d(t,{GG:()=>o,sB:()=>a});var n=r(3878);function i(){return"undefined"==typeof document||"complete"===document.readyState}function o(e,t){if(i())return e();(0,n.sp)("load",e,t)}function a(e){if(i())return e();(0,n.DD)("DOMContentLoaded",e)}},384:(e,t,r)=>{"use strict";r.d(t,{NT:()=>o,US:()=>d,Zm:()=>a,bQ:()=>c,dV:()=>s,nY:()=>u,pV:()=>l});var n=r(6154),i=r(1863);const o={beacon:"bam.nr-data.net",errorBeacon:"bam.nr-data.net"};function a(){return n.gm.NREUM||(n.gm.NREUM={}),void 0===n.gm.newrelic&&(n.gm.newrelic=n.gm.NREUM),n.gm.NREUM}function s(){let e=a();return e.o||(e.o={ST:n.gm.setTimeout,SI:n.gm.setImmediate,CT:n.gm.clearTimeout,XHR:n.gm.XMLHttpRequest,REQ:n.gm.Request,EV:n.gm.Event,PR:n.gm.Promise,MO:n.gm.MutationObserver,FETCH:n.gm.fetch,WS:n.gm.WebSocket}),e}function c(e,t){let r=a();r.initializedAgents??={},t.initializedAt={ms:(0,i.t)(),date:new Date},r.initializedAgents[e]=t}function u(e){let t=a();return t.initializedAgents?.[e]}function d(e,t){a()[e]=t}function l(){return function(){let e=a();const t=e.info||{};e.info={beacon:o.beacon,errorBeacon:o.errorBeacon,...t}}(),function(){let e=a();const t=e.init||{};e.init={...t}}(),s(),function(){let e=a();const t=e.loader_config||{};e.loader_config={...t}}(),a()}},2843:(e,t,r)=>{"use strict";r.d(t,{u:()=>i});var n=r(3878);function i(e,t=!1,r,i){(0,n.DD)("visibilitychange",(function(){if(t)return void("hidden"===document.visibilityState&&e());e(document.visibilityState)}),r,i)}},8139:(e,t,r)=>{"use strict";r.d(t,{u:()=>f});var n=r(7836),i=r(3434),o=r(8990),a=r(6154);const s={},c=a.gm.XMLHttpRequest,u="addEventListener",d="removeEventListener",l="nr@wrapped:".concat(n.P);function f(e){var t=function(e){return(e||n.ee).get("events")}(e);if(s[t.debugId]++)return t;s[t.debugId]=1;var r=(0,i.YM)(t,!0);function f(e){r.inPlace(e,[u,d],"-",g)}function g(e,t){return e[1]}return"getPrototypeOf"in Object&&(a.RI&&h(document,f),h(a.gm,f),h(c.prototype,f)),t.on(u+"-start",(function(e,t){var n=e[1];if(null!==n&&("function"==typeof n||"object"==typeof n)){var i=(0,o.I)(n,l,(function(){var e={object:function(){if("function"!=typeof n.handleEvent)return;return n.handleEvent.apply(n,arguments)},function:n}[typeof n];return e?r(e,"fn-",null,e.name||"anonymous"):n}));this.wrapped=e[1]=i}})),t.on(d+"-start",(function(e){e[1]=this.wrapped||e[1]})),t}function h(e,t,...r){let n=e;for(;"object"==typeof n&&!Object.prototype.hasOwnProperty.call(n,u);)n=Object.getPrototypeOf(n);n&&t(n,...r)}},3434:(e,t,r)=>{"use strict";r.d(t,{Jt:()=>o,YM:()=>c});var n=r(7836),i=r(5607);const o="nr@original:".concat(i.W);var a=Object.prototype.hasOwnProperty,s=!1;function c(e,t){return e||(e=n.ee),r.inPlace=function(e,t,n,i,o){n||(n="");const a="-"===n.charAt(0);for(let s=0;s<t.length;s++){const c=t[s],u=e[c];d(u)||(e[c]=r(u,a?c+n:n,i,c,o))}},r.flag=o,r;function r(t,r,n,s,c){return d(t)?t:(r||(r=""),nrWrapper[o]=t,function(e,t,r){if(Object.defineProperty&&Object.keys)try{return Object.keys(e).forEach((function(r){Object.defineProperty(t,r,{get:function(){return e[r]},set:function(t){return e[r]=t,t}})})),t}catch(e){u([e],r)}for(var n in e)a.call(e,n)&&(t[n]=e[n])}(t,nrWrapper,e),nrWrapper);function nrWrapper(){var o,a,d,l;try{a=this,o=[...arguments],d="function"==typeof n?n(o,a):n||{}}catch(t){u([t,"",[o,a,s],d],e)}i(r+"start",[o,a,s],d,c);try{return l=t.apply(a,o)}catch(e){throw i(r+"err",[o,a,e],d,c),e}finally{i(r+"end",[o,a,l],d,c)}}}function i(r,n,i,o){if(!s||t){var a=s;s=!0;try{e.emit(r,n,i,t,o)}catch(t){u([t,r,n,i],e)}s=a}}}function u(e,t){t||(t=n.ee);try{t.emit("internal-error",e)}catch(e){}}function d(e){return!(e&&"function"==typeof e&&e.apply&&!e[o])}},9300:(e,t,r)=>{"use strict";r.d(t,{T:()=>n});const n=r(860).K.ajax},3333:(e,t,r)=>{"use strict";r.d(t,{TZ:()=>n});const n=r(860).K.genericEvents},6774:(e,t,r)=>{"use strict";r.d(t,{T:()=>n});const n=r(860).K.jserrors},993:(e,t,r)=>{"use strict";r.d(t,{ET:()=>o,TZ:()=>a,p_:()=>i});var n=r(860);const i={ERROR:"ERROR",WARN:"WARN",INFO:"INFO",DEBUG:"DEBUG",TRACE:"TRACE"},o="log",a=n.K.logging},3785:(e,t,r)=>{"use strict";r.d(t,{R:()=>c,b:()=>u});var n=r(9908),i=r(1863),o=r(860),a=r(3969),s=r(993);function c(e,t,

In [ ]:
site = BeautifulSoup(response.text, 'html.parser') #faz a requisição passando  o  formato html

In [ ]:
site

<!DOCTYPE html>

<html lang="pt-BR">
<head><link href="https://www.google-analytics.com" rel="preconnect"/><link href="https://www.google.com" rel="preconnect"/><link href="https://data.mercadolibre.com" rel="preconnect"/><link href="https://http2.mlstatic.com" rel="preconnect"/><link href="https://stats.g.doubleclick.net" rel="preconnect"/><link href="https://analytics.mercadolivre.com.br" rel="preconnect"/><link href="https://analytics.mercadolivre.com" rel="preconnect"/><link href="https://www.google.com.br" rel="preconnect"/><script nonce="V2/xzcQr3yS1SStajWRGBQ==" type="text/javascript">window.NREUM||(NREUM={});NREUM.info = {"agent":"","beacon":"bam.nr-data.net","errorBeacon":"bam.nr-data.net","licenseKey":"NRBR-8547a290c864571ffcc","applicationID":"1729522169","agentToken":null,"applicationTime":765.346243,"transactionName":"bgQDMEcFXkJZBkYNWldOJBxFFlVCSw9BS3J8NU5LHw==","queueTime":0,"ttGuid":"2879607f54b120f7"}; (window.NREUM||(NREUM={})).init={privacy:{cookies_enabled:true},ajax:{deny_list:["bam.nr-data.net"]},distributed_tracing:{enabled:true}};(window.NREUM||(NREUM={})).loader_config={agentID:"1834861763",accountID:"989586",trustKey:"1709707",xpid:"XQ4OVF5VGwIHVlhXBQMGUF0=",licenseKey:"NRBR-8547a290c864571ffcc",applicationID:"1729522169"};;/*! For license information please see nr-loader-spa-1.267.0.min.js.LICENSE.txt */

In [ ]:
#procurar pela tag div e os atributos attrs

produto = site.find('div', attrs= {'class' : 'ui-search-result__wrapper'})

In [ ]:
print(produto)

<div class="ui-search-result__wrapper"><div class="andes-card ui-search-result ui-search-result--core andes-card--flat andes-card--padding-16" id=":R2l5e6:"><div class="ui-search-result__image"><section aria-label="Celular Samsung Galaxy A55 5g Dual Sim 128gb Rosa 8gb Ram" aria-roledescription="Carrossel" class="andes-carousel-snapped__container andes-carousel-snapped__container--full andes-carousel-snapped__container--with-controls" data-andes-carousel-snapped-main="true" id=":R2k2l5e6:"><div class="andes-carousel-snapped__header"></div><div class="andes-carousel-snapped__controls-wrapper"><button aria-label="Anterior" class="andes-carousel-snapped__control andes-carousel-snapped__control--previous andes-carousel-snapped__control--size-large andes-carousel-snapped__control--disabled" data-andes-carousel-snapped-control="previous" data-andes-state="disabled" disabled="" name="andes-carousel-snapped_control" type="button"><span><svg aria-hidden="true" fill="rgba(0, 0, 0, 0.9)" height="24" viewbox="0 0 24 24" width="24"><path d="M14.0656 4.9325L15.1263 5.99316L9.12254 11.9969L15.1325 18.0069L14.0719 19.0676L7.00122 11.9969L14.0656 4.9325Z" fill="rgba(0, 0, 0, 0.9)"></path></svg></span></button><div class="andes-carousel-snapped ui-search-result__card andes-carousel-snapped--scroll-hidden"><div class="andes-carousel-snapped__wrapper"><div aria-label="1 de 1" class="andes-carousel-snapped__slide" role="group" style="width:calc(100% - 0px)"><img alt="Celular Samsung Galaxy A55 5g Dual Sim 128gb Rosa 8gb Ram" class="ui-search-result-image__element lazy-loadable" decoding="sync" fetchpriority="high" height="160" src="https://http2.mlstatic.com/D_NQ_NP_629507-MLB79232794291_092024-V.webp" width="160"/></div></div></div><button aria-label="Seguinte" class="andes-carousel-snapped__control andes-carousel-snapped__control--next andes-carousel-snapped__control--size-large andes-carousel-snapped__control--disabled" data-andes-carousel-snapped-control="next" data-andes-state="disabled" disabled="" name="andes-carousel-snapped_control" type="button"><span><svg aria-hidden="true" fill="rgba(0, 0, 0, 0.9)" height="24" viewbox="0 0 24 24" width="24"><path d="M14.0656 4.9325L15.1263 5.99316L9.12254 11.9969L15.1325 18.0069L14.0719 19.0676L7.00122 11.9969L14.0656 4.9325Z" fill="rgba(0, 0, 0, 0.9)"></path></svg></span></button></div></section></div><div class="ui-search-result__content-wrapper"><div class="ui-search-item__group ui-search-item__group--title"><span class="ui-search-item__brand-discoverability ui-search-item__group__element">SAMSUNG</span><h2 aria-level="3" class="ui-search-item__title ui-search-item__group__element"><a class="ui-search-link__title-card ui-search-link" href="https://click1.mercadolivre.com.br/mclics/clicks/external/MLB/count?a=ArQxVdGUptIcSZ2XHbjpbyY4Y1nGYkxvtdmgWq%2Fk%2FLIycDzSVGcSbPaRgvuaxPO2cQDsN%2FCLVlhskLjoI7Nv4PVFwb3%2FocdLfGzSC1NhbVz9zviMrWoHcT2cWM0urvOwFxrTimqB9cIciAHCVC0OnodH9wKOMSjcC29p6nIR8z%2FDyg4AuCge3o57N5M6VACJEjkpTjpvnYm7sErEfpFX3S6WN1aHS9Yq%2BJye86wplJN4dWEnE7SPdzHf9yLo02aCtaS8Qhx6JgfkqIgUt3xFT304SO66FhITZF3By2DDKccYJZU7gh%2FRPsPgFLy8ZKh6gY7w4ABCQjd8GRQ5PeJOelwkANuDH3LeXm48bDIL30wE3MkI%2BYZ37X4UWLH%2BGZqxDTAGJ4bE1BWmQZDj%2BUBfDKoO0VyscCODVD8LJ2Cawib%2Fx7rL8aajD6ciWzyMzsT5XX3pk3rbeQEHaupv4dGvw2nzJ8jcim7JICMZvL5pICKg3TW3KHJUYzx91gVDKTB3VinG1anv12gkMHiKmikoqhGJW3ejI1MhNgHWOrWVO99UqQ4DoSVTw3Iw6ZnIofSFMC5i57ytMpGqe%2BykTjjGkADCegzb5LFKXprnTOw6wgYrV70jLqTgt3XvjBgcoOxDA3XqPPBRCCIyPg9y6GEPjQHg6Az5PHRKnQjQwtT%2FmNJsV5G%2BFCggiLi4YEA%2BcGpMP4wZkI4G1zW38Mn9v3sQEQ%3D%3D&amp;e=mclics%2Fpseudo-search-pads-buybox%2B7708&amp;rb=x" rel="nofollow,sponsored" title="Celular Samsung Galaxy A55 5g Dual Sim 128gb Rosa 8gb Ram">Celular Samsung Galaxy A55 5g Dual Sim 128gb Rosa 8gb Ram</a></h2><a class="ui-search-official-store-item__link ui-search-link" href="https://loja.mercadolivre.com.br/samsung" rel="nofollow,sponsored"><p class="ui-search-official-store-label ui-search-item__group__element ui-search-color--GRAY">Por Samsung<label class="ui-search-official-store-label__cockade ui-search-icon-label" for=""><span><svg aria-hidden="true" class="ui-search-icon ui-search-icon--cockade" fill="none" height="14" viewbox="0 0 14 14" width="14" xmlns="http://www.w3.org/2000/svg"><use href="#poly_cockade"></use></svg></span></label></p></a></div><div class="ui-search-result__content-columns"><div class="ui-search-result__content-column ui-search-result__content-column--left"><div class="ui-search-item__group ui-search-item__group--price ui-search-item__group--price-grid-container"><div class="ui-search-item__group__element ui-search-price__part-without-link"><div class="ui-search-price ui-search-price--size-medium"><s aria-label="Antes: 2799 reais" aria-roledescription="Preço" class="andes-money-amount ui-search-price__part ui-search-price__part--small ui-search-price__original-value andes-money-amount--previous andes-money-amount--cents-superscript andes-money-amount--compact" role="img" style="font-size:16px"><span aria-hidden="true" class="andes-money-amount__currency-symbol">R$</span><span aria-hidden="true" class="andes-money-amount__fraction">2.799</span></s><div class="ui-search-price__second-line"><span aria-label="2036 reais" aria-roledescription="Preço" class="andes-money-amount ui-search-price__part ui-search-price__part--medium andes-money-amount--cents-superscript" role="img" style="font-size:24px"><span aria-hidden="true" class="andes-money-amount__currency-symbol">R$</span><span aria-hidden="true" class="andes-money-amount__fraction">2.036</span></span><span class="ui-search-price__second-line__label"><span class="ui-search-price__discount">27% OFF</span></span></div></div></div><span class="ui-search-item__group__element ui-search-installments ui-search-color--LIGHT_GREEN"><div class="ui-search-installments-prefix"><span class="">em</span></div>10x <div class="ui-search-price ui-search-price--size-x-tiny ui-search-color--LIGHT_GREEN"><div class="ui-search-price__second-line"><span aria-label="203 reais com 62 centavos" aria-roledescription="Preço" class="andes-money-amount ui-search-price__part ui-search-price__part--x-tiny andes-money-amount--cents-superscript andes-money-amount--compact" role="img" style="font-size:16px"><span aria-hidden="true" class="andes-money-amount__currency-symbol">R$</span><span aria-hidden="true" class="andes-money-amount__fraction">203</span><span aria-hidden="true" class="andes-visually-hidden">,</span><span aria-hidden="true" class="andes-money-amount__cents andes-money-amount__cents--superscript-16" style="font-size:10px;margin-top:1px">62</span></span></div></div>sem juros</span></div><div class="ui-pb"><div class="ui-pb-container"><p class="ui-meliplus-pill meliplus--actived ui-pb-label-builder ui-meliplus-pill meliplus--actived meli_plus"><span class="ui-pb-highlight-wrapper"><span class="ui-pb-highlight-content"><span class="ui-pb-highlight" style="background:#FFFFFF;color:#00A650;padding-left:0;padding-right:0">Frete grátis</span></span></span></p></div></div><div class="ui-pb"><div class="ui-pb-container"><p class="fulfillment ui-pb-label-builder fulfillment fulfillment" style="color:#0000008C;font-size:12px;font-weight:400"><span aria-hidden="false" class="ui-pb-label">Enviado pelo</span><svg aria-label="full" class="ui-search-icon ui-search-icon--full" role="img" viewbox="0 0 100 32" xmlns="http://www.w3.org/2000/svg"><use href="#poly_full"></use></svg></p></div></div></div><div class="ui-search-result__content-column ui-search-result__content-column--right ui-search-result__content-column--extra-padding"><div class="ui-search-item__group ui-search-item__group--reviews"><div class="ui-search-reviews ui-search-item__group__element"><span class="andes-visually-hidden">Avaliação 4.9 de 5. 1,593 opiniões.</span><span aria-hidden="true" class="ui-search-reviews__rating-number">4.9</span><span aria-hidden="true" class="ui-search-reviews__ratings"><svg class="ui-search-icon ui-search-icon--star ui-search-icon--star-full" fill="#3483fa" height="100%" viewbox="0 0 10 10" width="100%"><use href="#poly_star_fill"></use></svg><svg class="ui-search-icon ui-search-icon--star ui-search-icon--star-full" fill="#3483fa" height="100%" viewbox="0 0 10 10" width="100%"><use href="#poly_star_fill"></use></svg><svg class="ui-search-icon ui-search-icon--star ui-search-icon--star-full" fill="#3483fa" height="100%" viewbox="0 0 10 10" width="100%"><use href="#poly_star_fill"></use></svg><svg class="ui-search-icon ui-search-icon--star ui-search-icon--star-full" fill="#3483fa" height="100%" viewbox="0 0 10 10" width="100%"><use href="#poly_star_fill"></use></svg><svg class="ui-search-icon ui-search-icon--star ui-search-icon--star-full" fill="#3483fa" height="100%" viewbox="0 0 10 10" width="100%"><use href="#poly_star_fill"></use></svg></span><span aria-hidden="true" class="ui-search-reviews__amount">(1593)</span></div></div></div></div><div class="ui-search-result__content-column ui-search-result__content-column--bottom"></div><div class="ui-search-item__pub-container"><a class="ui-search-item__pub-link ui-search-link" href="https://ads.mercadolivre.com.br/productAds?ui_version=v1&amp;utm_source=search_result_placement&amp;utm_medium=link&amp;utm_campaign=engagement" rel="nofollow" title="Patrocinado"><label class="ui-search-styled-label ui-search-item__pub-label" style="color:#999999">Patrocinado</label></a></div></div><div class="ui-search-result__bookmark"><form action="/search/bookmarks/MLB4552095970" class="ui-search-bookmark" method="POST"><button aria-checked="false" aria-label="Favorito" class="ui-search-bookmark__btn" role="switch" type="submit"><svg class="ui-search-icon ui-search-icon--bookmark ui-search-bookmark__icon-bookmark" viewbox="0 0 22 20" xmlns="http://www.w3.org/2000/svg"><use href="#poly_bookmark"></use></svg><svg class="ui-search-icon ui-search-icon--bookmark ui-search-bookmark__icon-bookmark-fill" viewbox="0 0 22 20" xmlns="http://www.w3.org/2000/svg"><use href="#poly_bookmark"></use></svg></button><input name="logginUrl" type="hidden" value="https://www.mercadolivre.com/jms/mlb/lgz/login?platform_id=ML&amp;go=https%3A%2F%2Flista.mercadolivre.com.br%2Fgalaxy&amp;loginType=explicit"/><input name="method" type="hidden" value="add"/><input name="itemId" type="hidden" value="MLB4552095970"/></form></div></div></div>

In [ ]:
links = produto.find('a', attrs={'class', 'ui-search-link'})

In [ ]:
print('Link do produto: ', links['href'])

Link do produto:  https://click1.mercadolivre.com.br/mclics/clicks/external/MLB/count?a=ArQxVdGUptIcSZ2XHbjpbyY4Y1nGYkxvtdmgWq%2Fk%2FLIycDzSVGcSbPaRgvuaxPO2cQDsN%2FCLVlhskLjoI7Nv4PVFwb3%2FocdLfGzSC1NhbVz9zviMrWoHcT2cWM0urvOwFxrTimqB9cIciAHCVC0OnodH9wKOMSjcC29p6nIR8z%2FDyg4AuCge3o57N5M6VACJEjkpTjpvnYm7sErEfpFX3S6WN1aHS9Yq%2BJye86wplJN4dWEnE7SPdzHf9yLo02aCtaS8Qhx6JgfkqIgUt3xFT304SO66FhITZF3By2DDKccYJZU7gh%2FRPsPgFLy8ZKh6gY7w4ABCQjd8GRQ5PeJOelwkANuDH3LeXm48bDIL30wE3MkI%2BYZ37X4UWLH%2BGZqxDTAGJ4bE1BWmQZDj%2BUBfDKoO0VyscCODVD8LJ2Cawib%2Fx7rL8aajD6ciWzyMzsT5XX3pk3rbeQEHaupv4dGvw2nzJ8jcim7JICMZvL5pICKg3TW3KHJUYzx91gVDKTB3VinG1anv12gkMHiKmikoqhGJW3ejI1MhNgHWOrWVO99UqQ4DoSVTw3Iw6ZnIofSFMC5i57ytMpGqe%2BykTjjGkADCegzb5LFKXprnTOw6wgYrV70jLqTgt3XvjBgcoOxDA3XqPPBRCCIyPg9y6GEPjQHg6Az5PHRKnQjQwtT%2FmNJsV5G%2BFCggiLi4YEA%2BcGpMP4wZkI4G1zW38Mn9v3sQEQ%3D%3D&e=mclics%2Fpseudo-search-pads-buybox%2B7708&rb=x

In [ ]:
#localizando o preço

real= produto.find('span', attrs={'class': 'andes-money-amount__fraction'})
preco = real.text.split()[0]
print(preco)

2.799

In [ ]:
#localizando o preço em outra ocorrencia.

real= produto.findAll('span', attrs={'class': 'andes-money-amount__fraction'})
preco = real[1]
print(preco.text)

2.036

In [ ]:
print('Preço do produto: R$ ', preco)

Preço do produto: R$  <span aria-hidden="true" class="andes-money-amount__fraction">2.036</span>

# Buscando todos os produtos

In [ ]:
url_base = 'https://lista.mercadolivre.com.br/'

In [ ]:
#criando um script

from numpy.lib.function_base import append
produto_nome=input('qual produto você procura? ')
response = requests.get(url_base + produto_nome)
site = BeautifulSoup(response.text, 'html.parser')
produtos= site.findAll('div', attrs= {'class':'ui-search-result__wrapper'})


a = []
for produto in produtos:

  links = produto.find('a', attrs={'class', 'ui-search-link'})
  real= produto.find('span', attrs={'class': 'andes-money-amount__fraction'})
  preco = real.text.split()[0]
  print('Link do produto: ', links['href'])
  print('Preço do produto: R$ ', preco)
  valor= preco
  a+=[valor]

  print('\n')

qual produto você procura? galaxy
Link do produto:  https://click1.mercadolivre.com.br/mclics/clicks/external/MLB/count?a=ulx2QyR13%2BYt3SCpCT4nY5OB9%2FMrjVTJJoK2Q38vD%2FDEpO1j1ckslDQ914zItURgEikKsbOCWB%2B77zav1hAB5MZCWx4fDnLurt6Q7nrcXRCZGt%2BKa1aRMCopCfKf7lOogqlGuzcbaGfLQyQeikhB3Ba1l6iFibFvmi41rqYgjSROGBucsU6OK8rt4WJcVdB6XqYyDIrAGoMgmRoapbkY2JqKjWB0uSSB3j3DEYd%2BsTOBqGejpFnrGhvzJEjlieIA2ShenmAZmMBRxgAbyDXd%2FCLv7DYCva3RgBwJ1ZODkqdOdrLiBY75NqHkfheuWY83eq3NoNZ5GdBcBoIxsRceCoeW8f1ObupgmkbnpJYvEVrSoQPoqJYzULN4cQ7WZe2p6kCmG6UEf4X5eahk3BNMom7Tm1Yrthx1NKEfBt3tOnsBVfKxIcdgwL36%2FgVeyUag4jz99ydBqXzxS2t9C5GR9AgXc35i75pjZp4VK0UxD4bVWbb%2B%2B0IZWHQdQJu4NvYVxNP1EpCF%2FgIMiTYsRFfml7wm4p1Mzm8dcBXWx%2ForrARuP0PdEktOmya9jBJn5ywyN3CUeubH%2B%2B1CM3gSCNcDa2eSFqytsciNv8HyqFf%2BYbcLbXSqc%2BuxV7Q7sFvm0AhhAHbF1FKRGR64FtYlBS95FkAX0rooTwpaGUNYd0vVsANMlqSF1q7zxTYZoX0jYTU%2Ftqtai4BUPi%2FcjEy%2FZWvBPFGi&e=mclics%2Fpseudo-search-pads-buybox%2B7708&rb=x
Preço do produto: R$  2.799


Link do produto:  https://click1.mercadolivre.com.br/mclics/clicks/external/MLB/count?a=5l5sJ28eG0QThuho4DHNbkH8lWe24WiYXOkfIjG4T2au7X3CBKyYXjNW%2FzJ%2B5xN6e6CpjtZRztCCMQLlnuf3P2JVh4uHu8beFwcodKtrTH06iUchCYXzweE4P4uK0ENiLjZp%2FUmp%2FPdhVClVeiHCatYfTzreG%2Fdg8Bbvd6auKA8ObYADKPiOBuIQiISKCUD1d3R1aKcHX%2FxjXK8eqAT3AOhHbXtXZ7A909BnI48Vm5zYGKJ7HipBhHnGxyWwthLedgXIPFEgC9Z6Qaql08cOb%2B9igBFTnN9gyBD3xclGF7NQqtIyCxf8G3waYd3n0tt8bglNmRY00YjCtN4msVrgzgABLhwLko7ZOrLJTuXXrHNPHFR%2BNvKy5PK3akpmIUGrXysvwNdnJN59f4biNntopONuCDSoNSdnkWLld8tXV%2BkkE1RfqLNxNsfkM56NexlxvMItPkISPQUjcHAggPIxS7%2BjkriV0mmKJl0tjROcXTEMdFMRPAA7hmtttfiOa2ciapTxGcFoyL8JJm7%2BfoUgmo877UlROSF%2B%2BhDOHuH3XoYKd31EQ8svHWZFkoegsjEQrKU1gsaQadO3kt8Sa1eC7AFopNscZMnqH44158SZUsMkbIJx1n4PDds6voXamx0Rdc0yftcZITvZGyfor%2FIcodB%2B8YPA%2BnG5qrVWNN3XCFGFin00ADKBNzYFO%2Bo%2Fa95iQ79Elk8GoEN%2B%2BQGHpMTX&e=mclics%2Fpseudo-search-pads-buybox%2B7708&rb=x
Preço do produto: R$  2.999


Link do produto:  https://www.mercadolivre.com.br/samsung-galaxy-a15-dual-sim-4g-256gb-azul-escuro-8gb-ram/p/MLB31214368#wid%3DMLB3616662829%26sid%3Dsearch%26searchVariation%3DMLB31214368%26position%3D8%26search_layout%3Dstack%26type%3Dproduct%26tracking_id%3D526429d9-fdb4-496c-8d9a-3b274a065d35
Preço do produto: R$  1.179


Link do produto:  https://www.mercadolivre.com.br/samsung-galaxy-s23-256-gb-5g-preto-8-gb-ram/p/MLB21436188#wid%3DMLB3303240037%26sid%3Dsearch%26searchVariation%3DMLB21436188%26position%3D10%26search_layout%3Dstack%26type%3Dproduct%26tracking_id%3D526429d9-fdb4-496c-8d9a-3b274a065d35
Preço do produto: R$  6.499


Link do produto:  https://www.mercadolivre.com.br/samsung-galaxy-a15-4g-dual-sim-128-gb-azul-escuro-4-gb-ram/p/MLB32175033#wid%3DMLB3589269609%26sid%3Dsearch%26searchVariation%3DMLB32175033%26position%3D5%26search_layout%3Dstack%26type%3Dproduct%26tracking_id%3D526429d9-fdb4-496c-8d9a-3b274a065d35
Preço do produto: R$  1.299


Link do produto:  https://www.mercadolivre.com.br/samsung-galaxy-s23-ultra-5g-dual-sim-256-gb-preto-12-gb-ram/p/MLB24594025#wid%3DMLB3555298458%26sid%3Dsearch%26searchVariation%3DMLB24594025%26position%3D4%26search_layout%3Dstack%26type%3Dproduct%26tracking_id%3D526429d9-fdb4-496c-8d9a-3b274a065d35
Preço do produto: R$  9.499


Link do produto:  https://www.mercadolivre.com.br/samsung-galaxy-a35-5g-dual-sim-256gb-azul-escuro-8-gb-ram/p/MLB34729843#wid%3DMLB3767334695%26sid%3Dsearch%26searchVariation%3DMLB34729843%26position%3D6%26search_layout%3Dstack%26type%3Dproduct%26tracking_id%3D526429d9-fdb4-496c-8d9a-3b274a065d35
Preço do produto: R$  2.831


Link do produto:  https://www.mercadolivre.com.br/samsung-galaxy-a05-dual-sim-128-gb-preto-4-gb-ram/p/MLB30395562#wid%3DMLB4580462572%26sid%3Dsearch%26searchVariation%3DMLB30395562%26position%3D9%26search_layout%3Dstack%26type%3Dproduct%26tracking_id%3D526429d9-fdb4-496c-8d9a-3b274a065d35
Preço do produto: R$  679


Link do produto:  https://www.mercadolivre.com.br/samsung-galaxy-a15-5g-5g-128-gb-verde-claro-4-gb-ram/p/MLB37291171#wid%3DMLB3641643589%26sid%3Dsearch%26searchVariation%3DMLB37291171%26position%3D3%26search_layout%3Dstack%26type%3Dproduct%26tracking_id%3D526429d9-fdb4-496c-8d9a-3b274a065d35
Preço do produto: R$  1.399


Link do produto:  https://www.mercadolivre.com.br/telefone-samsung-galaxy-a25-5g-dual-sim-256gb-azul-escuro-8gb-ram/p/MLB31498601#wid%3DMLB3615547375%26sid%3Dsearch%26searchVariation%3DMLB31498601%26position%3D12%26search_layout%3Dstack%26type%3Dproduct%26tracking_id%3D526429d9-fdb4-496c-8d9a-3b274a065d35
Preço do produto: R$  2.331


Link do produto:  https://www.mercadolivre.com.br/samsung-galaxy-a15-5g-dual-sim-128gb-azul-escuro-4gb-ram/p/MLB34103811#wid%3DMLB3609791441%26sid%3Dsearch%26searchVariation%3DMLB34103811%26position%3D14%26search_layout%3Dstack%26type%3Dproduct%26tracking_id%3D526429d9-fdb4-496c-8d9a-3b274a065d35
Preço do produto: R$  1.599


Link do produto:  https://www.mercadolivre.com.br/samsung-galaxy-a05s-128gb-dual-sim-tela-infinita-de-67-cor-prata-6gb-ram/p/MLB37699141#wid%3DMLB5008835776%26sid%3Dsearch%26searchVariation%3DMLB37699141%26position%3D16%26search_layout%3Dstack%26type%3Dproduct%26tracking_id%3D526429d9-fdb4-496c-8d9a-3b274a065d35
Preço do produto: R$  999


Link do produto:  https://www.mercadolivre.com.br/samsung-galaxy-a15-128-gb-azul-escuro-4-gb-ram/p/MLB32427104#wid%3DMLB4559665010%26sid%3Dsearch%26searchVariation%3DMLB32427104%26position%3D11%26search_layout%3Dstack%26type%3Dproduct%26tracking_id%3D526429d9-fdb4-496c-8d9a-3b274a065d35
Preço do produto: R$  1.270


Link do produto:  https://www.mercadolivre.com.br/samsung-galaxy-a15-5g-256-gb-azul-escuro-8-gb-ram/p/MLB37291177#wid%3DMLB3831411879%26sid%3Dsearch%26searchVariation%3DMLB37291177%26position%3D13%26search_layout%3Dstack%26type%3Dproduct%26tracking_id%3D526429d9-fdb4-496c-8d9a-3b274a065d35
Preço do produto: R$  1.119


Link do produto:  https://www.mercadolivre.com.br/celular-samsung-galaxy-a55-5g-cmera-tripla-ate-50mp-tela-66-256gb-azul-claro/p/MLB40303498#wid%3DMLB3841034319%26sid%3Dsearch%26searchVariation%3DMLB40303498%26position%3D15%26search_layout%3Dstack%26type%3Dproduct%26tracking_id%3D526429d9-fdb4-496c-8d9a-3b274a065d35
Preço do produto: R$  2.299


Link do produto:  https://www.mercadolivre.com.br/samsung-galaxy-a15-dual-sim-5g-256gb-azul-escuro-8gb-ram/p/MLB34103802#wid%3DMLB3837502169%26sid%3Dsearch%26searchVariation%3DMLB34103802%26position%3D17%26search_layout%3Dstack%26type%3Dproduct%26tracking_id%3D526429d9-fdb4-496c-8d9a-3b274a065d35
Preço do produto: R$  1.799


Link do produto:  https://www.mercadolivre.com.br/samsung-galaxy-s23-fe-exynos-5g-dual-sim-128-gb-creme-8-gb-ram/p/MLB27958233#wid%3DMLB3519197113%26sid%3Dsearch%26searchVariation%3DMLB27958233%26position%3D7%26search_layout%3Dstack%26type%3Dproduct%26tracking_id%3D526429d9-fdb4-496c-8d9a-3b274a065d35
Preço do produto: R$  3.999


Link do produto:  https://www.mercadolivre.com.br/samsung-galaxy-a55-128gb-8gb-awesome-navy/p/MLB38283469#wid%3DMLB3849891053%26sid%3Dsearch%26searchVariation%3DMLB38283469%26position%3D18%26search_layout%3Dstack%26type%3Dproduct%26tracking_id%3D526429d9-fdb4-496c-8d9a-3b274a065d35
Preço do produto: R$  2.498


Link do produto:  https://www.mercadolivre.com.br/samsung-galaxy-a35-5g-dual-sim-128-gb-rosa-6-gb-ram/p/MLB35331184#wid%3DMLB4662999930%26sid%3Dsearch%26searchVariation%3DMLB35331184%26position%3D22%26search_layout%3Dstack%26type%3Dproduct%26tracking_id%3D526429d9-fdb4-496c-8d9a-3b274a065d35
Preço do produto: R$  1.849


Link do produto:  https://www.mercadolivre.com.br/samsung-galaxy-a06-dual-sim-128-gb-verde-claro-4-gb-ram/p/MLB40822887#wid%3DMLB5048123802%26sid%3Dsearch%26searchVariation%3DMLB40822887%26position%3D19%26search_layout%3Dstack%26type%3Dproduct%26tracking_id%3D526429d9-fdb4-496c-8d9a-3b274a065d35
Preço do produto: R$  899


Link do produto:  https://www.mercadolivre.com.br/celular-samsung-galaxy-m55-5g-dual-sim-256-gb-azul-escuro-8-gb-ram/p/MLB36208238#wid%3DMLB3838214415%26sid%3Dsearch%26searchVariation%3DMLB36208238%26position%3D23%26search_layout%3Dstack%26type%3Dproduct%26tracking_id%3D526429d9-fdb4-496c-8d9a-3b274a065d35
Preço do produto: R$  2.399


Link do produto:  https://www.mercadolivre.com.br/samsung-galaxy-a14-5g-5g-128-gb-preto-4-gb-ram/p/MLB36484947#wid%3DMLB3850887819%26sid%3Dsearch%26searchVariation%3DMLB36484947%26position%3D20%26search_layout%3Dstack%26type%3Dproduct%26tracking_id%3D526429d9-fdb4-496c-8d9a-3b274a065d35
Preço do produto: R$  1.599


Link do produto:  https://www.mercadolivre.com.br/samsung-galaxy-a06-dual-sim-128-gb-branco-4-gb-ram/p/MLB40822891#wid%3DMLB5048097892%26sid%3Dsearch%26searchVariation%3DMLB40822891%26position%3D21%26search_layout%3Dstack%26type%3Dproduct%26tracking_id%3D526429d9-fdb4-496c-8d9a-3b274a065d35
Preço do produto: R$  899


Link do produto:  https://www.mercadolivre.com.br/samsung-galaxy-a54-5g-256gb-preto-8gb-ram/p/MLB23138587#wid%3DMLB3753358769%26sid%3Dsearch%26searchVariation%3DMLB23138587%26position%3D51%26search_layout%3Dstack%26type%3Dproduct%26tracking_id%3D526429d9-fdb4-496c-8d9a-3b274a065d35
Preço do produto: R$  2.374


Link do produto:  https://www.mercadolivre.com.br/celular-samsung-galaxy-m35-5g-cmera-tripla-ate-50mp-selfie-50mp-tela-super-amoled-66-120hz-256gb-8gb-ram-azul-claro/p/MLB37105949#wid%3DMLB4993013384%26sid%3Dsearch%26searchVariation%3DMLB37105949%26position%3D29%26search_layout%3Dstack%26type%3Dproduct%26tracking_id%3D526429d9-fdb4-496c-8d9a-3b274a065d35
Preço do produto: R$  1.649


Link do produto:  https://www.mercadolivre.com.br/samsung-galaxy-a34-5g-256-gb-preto-8-gb-ram/p/MLB22385545#wid%3DMLB3708013908%26sid%3Dsearch%26searchVariation%3DMLB22385545%26position%3D27%26search_layout%3Dstack%26type%3Dproduct%26tracking_id%3D526429d9-fdb4-496c-8d9a-3b274a065d35
Preço do produto: R$  1.949


Link do produto:  https://www.mercadolivre.com.br/smartphone-galaxy-a13-66-128gb-4gb-ram-preto-samsung/p/MLB19077030#wid%3DMLB4963470794%26sid%3Dsearch%26searchVariation%3DMLB19077030%26position%3D30%26search_layout%3Dstack%26type%3Dproduct%26tracking_id%3D526429d9-fdb4-496c-8d9a-3b274a065d35
Preço do produto: R$  1.449


Link do produto:  https://www.mercadolivre.com.br/samsung-galaxy-a05s-128-gb-preto-4-gb-ram/p/MLB37974111#wid%3DMLB3796572901%26sid%3Dsearch%26searchVariation%3DMLB37974111%26position%3D44%26search_layout%3Dstack%26type%3Dproduct%26tracking_id%3D526429d9-fdb4-496c-8d9a-3b274a065d35
Preço do produto: R$  1.059


Link do produto:  https://www.mercadolivre.com.br/samsung-galaxy-a35-5g-128gb-azul-escuro-6gb-ram/p/MLB34729846#wid%3DMLB3809393261%26sid%3Dsearch%26searchVariation%3DMLB34729846%26position%3D36%26search_layout%3Dstack%26type%3Dproduct%26tracking_id%3D526429d9-fdb4-496c-8d9a-3b274a065d35
Preço do produto: R$  1.579


Link do produto:  https://www.mercadolivre.com.br/samsung-celular-galaxy-a55-5g-cmera-tripla-ate-50mp-tela-66-256gb-azul-escuro/p/MLB40585828#wid%3DMLB3861851251%26sid%3Dsearch%26searchVariation%3DMLB40585828%26position%3D34%26search_layout%3Dstack%26type%3Dproduct%26tracking_id%3D526429d9-fdb4-496c-8d9a-3b274a065d35
Preço do produto: R$  2.499


Link do produto:  https://www.mercadolivre.com.br/samsung-galaxy-j4-dual-sim-32-gb-preto-2-gb-ram/p/MLB9928420#wid%3DMLB3861595831%26sid%3Dsearch%26searchVariation%3DMLB9928420%26position%3D41%26search_layout%3Dstack%26type%3Dproduct%26tracking_id%3D526429d9-fdb4-496c-8d9a-3b274a065d35
Preço do produto: R$  622


Link do produto:  https://www.mercadolivre.com.br/samsung-galaxy-s23-fe-5g-dual-sim-256-gb-grafite-8-gb-ram/p/MLB27957682#wid%3DMLB4936752132%26sid%3Dsearch%26searchVariation%3DMLB27957682%26position%3D24%26search_layout%3Dstack%26type%3Dproduct%26tracking_id%3D526429d9-fdb4-496c-8d9a-3b274a065d35
Preço do produto: R$  2.710


Link do produto:  https://www.mercadolivre.com.br/samsung-galaxy-a10-dual-sim-32-gb-preto-2-gb-ram/p/MLB14648948#wid%3DMLB4156526760%26sid%3Dsearch%26searchVariation%3DMLB14648948%26position%3D28%26search_layout%3Dstack%26type%3Dproduct%26tracking_id%3D526429d9-fdb4-496c-8d9a-3b274a065d35
Preço do produto: R$  899


Link do produto:  https://www.mercadolivre.com.br/celular-samsung-galaxy-a25-5g-cmera-tripla-traseira-de-ate-50mp-selfie-de-13mp-tela-infinita-super-amoled-de-65-120-hz-128gb-6gb-processador-octa-core-dual-chip-azul-escuro/p/MLB34103803#wid%3DMLB3677512277%26sid%3Dsearch%26searchVariation%3DMLB34103803%26position%3D31%26search_layout%3Dstack%26type%3Dproduct%26tracking_id%3D526429d9-fdb4-496c-8d9a-3b274a065d35
Preço do produto: R$  1.409


Link do produto:  https://www.mercadolivre.com.br/samsung-galaxy-a23-128-gb-black-4-gb-ram/p/MLB19144872#wid%3DMLB3846776273%26sid%3Dsearch%26searchVariation%3DMLB19144872%26position%3D39%26search_layout%3Dstack%26type%3Dproduct%26tracking_id%3D526429d9-fdb4-496c-8d9a-3b274a065d35
Preço do produto: R$  1.469


Link do produto:  https://www.mercadolivre.com.br/samsung-galaxy-s24-ultra-5g-dual-sim-512-gb-titnio-preto-12-gb-ram/p/MLB29893932#wid%3DMLB3861492611%26sid%3Dsearch%26searchVariation%3DMLB29893932%26position%3D25%26search_layout%3Dstack%26type%3Dproduct%26tracking_id%3D526429d9-fdb4-496c-8d9a-3b274a065d35
Preço do produto: R$  6.099


Link do produto:  https://www.mercadolivre.com.br/smartphone-galaxy-a33-5g-64-128gb-6gb-ram-preto-samsung/p/MLB19108225#wid%3DMLB5082356262%26sid%3Dsearch%26searchVariation%3DMLB19108225%26position%3D32%26search_layout%3Dstack%26type%3Dproduct%26tracking_id%3D526429d9-fdb4-496c-8d9a-3b274a065d35
Preço do produto: R$  1.430


Link do produto:  https://www.mercadolivre.com.br/samsung-galaxy-a10s-tela-62-32gb-2gb-ram-preto/p/MLB15157294#wid%3DMLB2088477224%26sid%3Dsearch%26searchVariation%3DMLB15157294%26position%3D26%26search_layout%3Dstack%26type%3Dproduct%26tracking_id%3D526429d9-fdb4-496c-8d9a-3b274a065d35
Preço do produto: R$  1.099


Link do produto:  https://www.mercadolivre.com.br/smartphone-samsung-galaxy-a06-4g-128gb-4gb-ram-dual-chip-cmera-traseira-502mp-frontal-8mp-tela-67-azul-escuro/p/MLB40304330#wid%3DMLB5058803466%26sid%3Dsearch%26searchVariation%3DMLB40304330%26position%3D35%26search_layout%3Dstack%26type%3Dproduct%26tracking_id%3D526429d9-fdb4-496c-8d9a-3b274a065d35
Preço do produto: R$  859


Link do produto:  https://www.mercadolivre.com.br/samsung-galaxy-a54-5g-256gb-8gb-ram-preto/p/MLB22770354#wid%3DMLB4113072938%26sid%3Dsearch%26searchVariation%3DMLB22770354%26position%3D37%26search_layout%3Dstack%26type%3Dproduct%26tracking_id%3D526429d9-fdb4-496c-8d9a-3b274a065d35
Preço do produto: R$  2.068


Link do produto:  https://produto.mercadolivre.com.br/MLB-4936091510-samsung-galaxy-s10-128-gb-c-mancha-na-tela-detalhe-no-aro-_JM?searchVariation=181172484592#searchVariation%3D181172484592%26position%3D52%26search_layout%3Dstack%26type%3Ditem%26tracking_id%3D526429d9-fdb4-496c-8d9a-3b274a065d35
Preço do produto: R$  849


Link do produto:  https://www.mercadolivre.com.br/samsung-galaxy-m34-5g-128gb-6gb-ram-mega-bateria-6000mah-cmera-tripla-50mp82-octacore-65-120hz-azul-marinho/p/MLB27145713#wid%3DMLB4995747604%26sid%3Dsearch%26searchVariation%3DMLB27145713%26position%3D38%26search_layout%3Dstack%26type%3Dproduct%26tracking_id%3D526429d9-fdb4-496c-8d9a-3b274a065d35
Preço do produto: R$  1.480


Link do produto:  https://www.mercadolivre.com.br/smartphone-galaxy-a51-tela-65-128gb-4gb-ram-branco-samsung/p/MLB15466967#wid%3DMLB5063674024%26sid%3Dsearch%26searchVariation%3DMLB15466967%26position%3D40%26search_layout%3Dstack%26type%3Dproduct%26tracking_id%3D526429d9-fdb4-496c-8d9a-3b274a065d35
Preço do produto: R$  1.690


Link do produto:  https://www.mercadolivre.com.br/smartphone-galaxy-a12-tela-65-64gb-4gb-ram-branco-samsung-cor-white/p/MLB17323812#wid%3DMLB1889324009%26sid%3Dsearch%26searchVariation%3DMLB17323812%26position%3D43%26search_layout%3Dstack%26type%3Dproduct%26tracking_id%3D526429d9-fdb4-496c-8d9a-3b274a065d35
Preço do produto: R$  1.399


Link do produto:  https://www.mercadolivre.com.br/smartphone-samsung-galaxy-a11-tl-64-64gb-3gb-ram-preto/p/MLB15946509#wid%3DMLB3921849118%26sid%3Dsearch%26searchVariation%3DMLB15946509%26position%3D33%26search_layout%3Dstack%26type%3Dproduct%26tracking_id%3D526429d9-fdb4-496c-8d9a-3b274a065d35
Preço do produto: R$  999


Link do produto:  https://www.mercadolivre.com.br/samsung-galaxy-a12-64-gb-branco-4-gb-ram/p/MLB18640203#wid%3DMLB3438106305%26sid%3Dsearch%26searchVariation%3DMLB18640203%26position%3D42%26search_layout%3Dstack%26type%3Dproduct%26tracking_id%3D526429d9-fdb4-496c-8d9a-3b274a065d35
Preço do produto: R$  1.157


Link do produto:  https://www.mercadolivre.com.br/samsung-galaxy-a31-128-gb-prism-crush-black-4-gb-ram/p/MLB15809289#wid%3DMLB3849245473%26sid%3Dsearch%26searchVariation%3DMLB15809289%26position%3D45%26search_layout%3Dstack%26type%3Dproduct%26tracking_id%3D526429d9-fdb4-496c-8d9a-3b274a065d35
Preço do produto: R$  1.382


Link do produto:  https://www.mercadolivre.com.br/celular-samsung-galaxy-a25-5g-cmera-tripla-traseira-de-ate-50mp-selfie-de-13mp-tela-infinita-super-amoled-de-65-120-hz-128gb-6gb-processador-octa-core-dual-chip-azul/p/MLB32285149#wid%3DMLB3677538633%26sid%3Dsearch%26searchVariation%3DMLB32285149%26position%3D46%26search_layout%3Dstack%26type%3Dproduct%26tracking_id%3D526429d9-fdb4-496c-8d9a-3b274a065d35
Preço do produto: R$  1.409


Link do produto:  https://www.mercadolivre.com.br/samsung-galaxy-s24-5g-dual-sim-256-gb-creme-8-gb-ram/p/MLB29761875#wid%3DMLB4392386868%26sid%3Dsearch%26searchVariation%3DMLB29761875%26position%3D49%26search_layout%3Dstack%26type%3Dproduct%26tracking_id%3D526429d9-fdb4-496c-8d9a-3b274a065d35
Preço do produto: R$  6.499


Link do produto:  https://www.mercadolivre.com.br/smartphone-samsung-galaxy-a71-tela-67-128gb-6gb-ram-android-cor-preto/p/MLB15506596#wid%3DMLB5071447436%26sid%3Dsearch%26searchVariation%3DMLB15506596%26position%3D48%26search_layout%3Dstack%26type%3Dproduct%26tracking_id%3D526429d9-fdb4-496c-8d9a-3b274a065d35
Preço do produto: R$  1.918


Link do produto:  https://www.mercadolivre.com.br/samsung-galaxy-j7-dual-sim-16-gb-dourado-15-gb-ram/p/MLB6143476#wid%3DMLB3824692035%26sid%3Dsearch%26searchVariation%3DMLB6143476%26position%3D50%26search_layout%3Dstack%26type%3Dproduct%26tracking_id%3D526429d9-fdb4-496c-8d9a-3b274a065d35
Preço do produto: R$  614


Link do produto:  https://www.mercadolivre.com.br/smartphone-samsung-galaxy-a01-core-tela-53-32gb-2gb-ram-pto-cor-preto/p/MLB16107489#wid%3DMLB3219559397%26sid%3Dsearch%26searchVariation%3DMLB16107489%26position%3D47%26search_layout%3Dstack%26type%3Dproduct%26tracking_id%3D526429d9-fdb4-496c-8d9a-3b274a065d35
Preço do produto: R$  849

In [ ]:
print(a)

['2.799', '2.999', '1.179', '6.499', '1.299', '9.499', '2.831', '679', '1.399', '2.331', '1.599', '999', '1.270', '1.119', '2.299', '1.799', '3.999', '2.498', '1.849', '899', '2.399', '1.599', '899', '2.374', '1.649', '1.949', '1.449', '1.059', '1.579', '2.499', '622', '2.710', '899', '1.409', '1.469', '6.099', '1.430', '1.099', '859', '2.068', '849', '1.480', '1.690', '1.399', '999', '1.157', '1.382', '1.409', '6.499', '1.918', '614', '849']

In [ ]:
dados = pd.DataFrame(a)
dados.columns = ['Preço']

In [ ]:
dados

    Preço
0   2.799
1   2.999
2   1.179
3   6.499
4   1.299
5   9.499
6   2.831
7     679
8   1.399
9   2.331
10  1.599
11    999
12  1.270
13  1.119
14  2.299
15  1.799
16  3.999
17  2.498
18  1.849
19    899
20  2.399
21  1.599
22    899
23  2.374
24  1.649
25  1.949
26  1.449
27  1.059
28  1.579
29  2.499
30    622
31  2.710
32    899
33  1.409
34  1.469
35  6.099
36  1.430
37  1.099
38    859
39  2.068
40    849
41  1.480
42  1.690
43  1.399
44    999
45  1.157
46  1.382
47  1.409
48  6.499
49  1.918
50    614
51    849

In [ ]:
dados['Preço'] = pd.to_numeric(dados['Preço'])
dados.head()

   Preço
0  2.799
1  2.999
2  1.179
3  6.499
4  1.299